#!/usr/bin/bash
#
# Copyright (C) 2018 and later, Indie Computing Corp. All rights reserved. License: see package.
#

post_install() {
    systemd-sysusers
    chsh --shell /bin/bash mastodon > /dev/null 2>&1
}

post_upgrade() {
    systemd-sysusers
    chsh --shell /bin/bash mastodon > /dev/null 2>&1
}
